 ## Switches
set_property PACKAGE_PIN V17 [get_ports {D}]                                       
        set_property IOSTANDARD LVCMOS33 [get_ports {D}]
set_property PACKAGE_PIN V16 [get_ports {C}]                                       
        set_property IOSTANDARD LVCMOS33 [get_ports {C}]
set_property PACKAGE_PIN W16 [get_ports {B}]                                       
        set_property IOSTANDARD LVCMOS33 [get_ports {B}]
set_property PACKAGE_PIN W17 [get_ports {A}]                                       
        set_property IOSTANDARD LVCMOS33 [get_ports {A}]
        
##7 segment display
set_property PACKAGE_PIN W7 [get_ports {p}]                                       
        set_property IOSTANDARD LVCMOS33 [get_ports {p}]
set_property PACKAGE_PIN W6 [get_ports {q}]                                       
        set_property IOSTANDARD LVCMOS33 [get_ports {q}]
set_property PACKAGE_PIN U8 [get_ports {r}]                                       
        set_property IOSTANDARD LVCMOS33 [get_ports {r}]
set_property PACKAGE_PIN V8 [get_ports {s}]                                       
        set_property IOSTANDARD LVCMOS33 [get_ports {s}]
set_property PACKAGE_PIN U5 [get_ports {t}]                                       
        set_property IOSTANDARD LVCMOS33 [get_ports {t}]
set_property PACKAGE_PIN V5 [get_ports {u}]                                       
        set_property IOSTANDARD LVCMOS33 [get_ports {u}]
set_property PACKAGE_PIN U7 [get_ports {v}]                                       
        set_property IOSTANDARD LVCMOS33 [get_ports {v}]

set_property PACKAGE_PIN U2 [get_ports {an0}]                                        
        set_property IOSTANDARD LVCMOS33 [get_ports {an0}]
set_property PACKAGE_PIN U4 [get_ports {an1}]                                        
        set_property IOSTANDARD LVCMOS33 [get_ports {an1}]
set_property PACKAGE_PIN V4 [get_ports {an2}]                                        
        set_property IOSTANDARD LVCMOS33 [get_ports {an2}]
set_property PACKAGE_PIN W4 [get_ports {an3}]                                        
        set_property IOSTANDARD LVCMOS33 [get_ports {an3}]